version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: looker_chatbot_db
    environment:
      POSTGRES_DB: looker_chatbot
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d looker_chatbot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: